CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    price       DOUBLE PRECISION                        NOT NULL,
    quantity    INTEGER                                 NOT NULL,
    size        VARCHAR(255),
    color       VARCHAR(255),
    image_url   VARCHAR(255),
    category_id BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);