name: Build and push to Docker HUB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build application
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: List contents of target/
        run: ls -lh target/

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: demo1
          path: target/*.jar  # 👈 this will now match correctly

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: demo1
          path: target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/demo1:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/demo1:${{ github.sha }}
